-- AlterTable
ALTER TABLE "AlertSettings" ADD COLUMN "ttsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AlertSettings" ADD COLUMN "ttsVoice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AlertSettings" ADD COLUMN "ttsRate" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE "AlertSettings" ADD COLUMN "ttsVolume" INTEGER NOT NULL DEFAULT 80;
